"""create description and brand columns to products

Revision ID: f019af109a83
Revises: abb6f6aa2e2b
Create Date: 2026-01-09 19:15:14.718211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f019af109a83'
down_revision: Union[str, None] = 'abb6f6aa2e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=120), nullable=False))
    op.add_column('products', sa.Column('brand', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
